"""

initital psuedocode for A* generated by Claude Sonnet

"""



import heapq
import numpy as np

# BELT_TO_NORTH           = 0b0001
# BELT_TO_EAST            = 0b0010
# BELT_TO_SOUTH           = 0b0100
# BELT_TO_WEST            = 0b1000
# # BELT_INPUT_GOING_NORTH  = BELT_TO_NORTH << 4
# # BELT_INPUT_GOING_EAST   = BELT_TO_EAST  << 4
# # BELT_INPUT_GOING_SOUTH  = BELT_TO_SOUTH << 4
# # BELT_INPUT_GOING_WEST   = BELT_TO_WEST  << 4
#           # underground distance will be specified in bits 5-8

DIRECTIONS = [
    ("n",  0, -1 ),
    ("e",  1,  0 ),
    ("s",  0,  1 ),
    ("w", -1,  0 )
]

MAX_UNDERGROUND = 4

BELT_MOVESET = {
    #           ds  iron_cost path_bitmask                  can_turn_next
    "belt":   ( 1,   3.0,     0b00000001   ),   # np.array((1,)),            True          ),
}

UNDERGROUND_MASK = 0b0011110
UNDERGROUND_MOVESET = {
    #           ds  iron_cost path_bitmask
    "under1": ( 4,  21.5,     0b00001101   ),   # np.array((1,0,1,1)),       False         ),
    "under2": ( 5,  21.5,     0b00011001   ),   # np.array((1,0,0,1,1)),     False         ),
    "under3": ( 6,  21.5,     0b00110001   ),   # np.array((1,0,0,0,1,1)),   False         ),
    "under4": ( 7,  21.5,     0b01100001   ),   # np.array((1,0,0,0,0,1,1)), False         )
}
MAX_BELT_MOVESET_LENGTH = max(UNDERGROUND_MOVESET.values(), key=lambda x:x[0])[0]

# OBSTACLE_KINDS = {
#     "belt segment",
#     "belt turn",

#     "underground start/end pair",

#     "other entity"
# }
# OPERATION_KINDS = {
#     "add belt step",
#     "build underground",
#     "pierce through existing belt segment"
# }

class Entity:
    def __init__(self, x, y, direction) -> None:
        self.x = x
        self.y = y
        self.direction = direction
class BeltSegment(Entity):
    def __init__(self, start_x, start_y, direction, length) -> None:
        super().__init__(start_x, start_y, direction)
        self.length = length
    def get_index_at(self, x, y):
        _, dx, dy = DIRECTIONS[self.direction]
        if dx != 0:
            return (x - self.x) // dx
        elif dy != 0:
            return (y - self.y) // dy
        else:
            assert False
class BeltCorner(Entity):
    def __init__(self, x, y, direction) -> None:
        super().__init__(x, y, direction)
        raise NotImplementedError

class BeltOperation:
    def __init__(self, x, y, direction, previous_direction, ds, iron_cost) -> None:
        self.x = x
        self.y = y
        self.direction = direction
        self.previous_direction = previous_direction
        self.ds = int(ds)
        self.iron_cost = float(iron_cost)

        self.g_cost = 0
        self.g_cost += ds*1.0
        self.g_cost += iron_cost*0.001
        if direction != previous_direction: self.g_cost += 0.0001
class AddBeltStep(BeltOperation):
    def __init__(self, x, y, direction, previous_direction) -> None:
        super().__init__(x, y, direction, previous_direction, 1, 3.0)
class BuildUnderground(BeltOperation):
    def __init__(self, x, y, direction, previous_direction, underground_size) -> None:
        super().__init__(x, y, direction, previous_direction, underground_size+3, 21.5)
        self.underground_size = underground_size
class PierceThroughBelt(BeltOperation):
    def __init__(self, x, y, direction, previous_direction, segment_to_pierce:BeltSegment) -> None:
        raise NotImplementedError
        super().__init__(x, y, direction, previous_direction, 1, )
        self.segment_to_pierce = segment_to_pierce


# def cost(ds, iron_cost, direction, previous_direction):
#     c = 0
#     c += ds*1.0
#     c += iron_cost*0.001
#     if direction != previous_direction: c += 0.0001
#     return c

def neighbors(obstacle_grid, obstacle_table, previous_operation:BeltOperation|None, xy):
    bitmap_shape = obstacle_grid.shape

    # if previous_xy[1] > y:
    #     direction = 0
    # elif previous_xy[0] < x:
    #     direction = 1
    # elif previous_xy[1] < y:
    #     direction = 2
    # elif previous_xy[0] > x:
    #     direction = 3
    # else:
    #     raise ValueError("previous xy is equal to current xy")

    # for (direction, (cardinal, dx, dy)) in enumerate(DIRECTIONS):
    #     if previous_direction != None and direction == (previous_direction + 2) % 4:
    #         continue # cannot double back

    x, y = xy

    # previous_operation_kind = previous_operation[0]
    # assert previous_operation_kind in OPERATION_KINDS
    # if previous_operation_kind == "add belt step":
    #     _, prevx, prevy, 
    if previous_operation == None:
        previous_direction = None
        valid_directions = (0, 1, 2, 3)
    else:
        # print(previous_direction)
        previous_direction = previous_operation.direction
        valid_directions = (previous_direction, (previous_direction+1)%4, (previous_direction-1)%4)

    for direction in valid_directions:
        (cardinal, dx, dy) = DIRECTIONS[direction]
        

        # if obstacle_grid[y+dy, x+dx]:
        #     yield "parallel intersection: ask for other to make underground (if possible)"
        #     # ==> medium cost
        # else:
        #     for underground_length in range(MAX_UNDERGROUND):
        #         if obstacle_grid[y+dy*2, x+dx*2]
        #     if obstacle_grid[y+dy*2, x+dx*2] and obstacle_grid[x:x+dx*4:dx].any():
        #         # for under in range(MAX_UNDERGROUND)
        #         yield "cross intersection: let's make an underground"
        #         # ==> medium cost

        #     yield "regular belt"
        #     # ==> low cost





        for move_name, (ds, iron_cost, path_bitmask) in BELT_MOVESET.items():
            nx = x + ds*dx
            ny = y + ds*dy
            cell_contents = obstacle_grid[ny, nx]
                

            # if space ahead is free, yield a standard belt forwards

            if cell_contents == 0:
                # yield format: (g_cost, obstacle_aka_operation_data)
                yield AddBeltStep(nx, ny, direction, previous_direction)
        

            # special new feature
            #  if the cell ahead is:
            #   -> part of a belt segment (found by lookup in the obstacle table)
            #   -> not the first or last belt of the segment
            #  then, yield this option:
            #   -> cut through the existing belt (force it to make an underground)
            #      (the cost is based on the existing belt making the longest possible underground)

            else:
                obstacle_data = obstacle_table[cell_contents]
                # obstacle_kind = obstacle_data[0]

                # assert obstacle_kind in OBSTACLE_KINDS, (obstacle_kind, obstacle_data)

                # if obstacle_kind == "belt segment":
                if isinstance(obstacle_data, BeltSegment):
                    # note that "belt segment" is distinct from "belt turn", so since we can't underground in a corner

                    # _, segment_startx, segment_starty, segment_direction, segment_length = obstacle_data

                    # if segment_direction == 0 or segment_direction == 2: # north/south
                    # displacement_from_segment_start = np.subtract((obstacle_data.x, obstacle_data.y), (nx, ny))
                    # if dx != 0:
                    #     current_index_of_segment = displacement_from_segment_start[0] // dx
                    # elif dy != 0:
                    #     current_index_of_segment = displacement_from_segment_start[1] // dy
                    # else:
                    #     raise ValueError((dx, dy))
                    current_index_of_segment = obstacle_data.get_index_at(nx, ny)

                    if current_index_of_segment > 0 and current_index_of_segment < obstacle_data.length-1:
                        underground_size = min(obstacle_data.length-2, 4) # length from 1:-1 (skip the start and end)

                        # underground_move = UNDERGROUND_MOVESET[f"under{underground_size}"]
                        # under_ds = underground_move[0]
                        # under_iron_cost = underground_move[1]
                        # existing_belt_cost = cost(under_ds, under_ds*iron_cost, segment_direction, segment_direction)
                        # underground_cost = cost(under_ds, under_iron_cost, segment_direction, segment_direction)

                        # additional_cost = cost(ds, iron_cost, direction, previous_direction)
                        # c = additional_cost + underground_cost - existing_belt_cost

                        # yield dsfdsf
                        # yield c, ("pierce through existing belt segment", x+dx, y+dy, direction, 1, underground_size)
                        yield PierceThroughBelt(nx, ny, direction, previous_direction, obstacle_data)



        # if an underground belt could be necessary in the future, yield that option

        mask_minx = min(x + dx, x + dx*MAX_BELT_MOVESET_LENGTH)
        mask_maxx = max(x + dx, x + dx*MAX_BELT_MOVESET_LENGTH)
        mask_miny = min(y + dy, y + dy*MAX_BELT_MOVESET_LENGTH)
        mask_maxy = max(y + dy, y + dy*MAX_BELT_MOVESET_LENGTH)
        
        obstacle_bool_arr = (obstacle_grid[mask_miny:mask_maxy+1, mask_minx:mask_maxx+1] > 0).ravel()
        if dx == -1 or dy == -1:
            obstacle_bool_arr = obstacle_bool_arr[::-1]
        obstacle_bitmask = int.from_bytes(np.packbits(obstacle_bool_arr, bitorder="little").tobytes())

        if obstacle_bitmask & UNDERGROUND_MASK:
            for move_name, (ds, iron_cost, path_bitmask) in UNDERGROUND_MOVESET.items():
                nx = x + ds*dx
                ny = y + ds*dy

                # is it in bounds
                if nx < 0:
                    continue
                if ny < 0:
                    continue
                if nx >= bitmap_shape[1]: # x vs columns
                    continue
                if ny >= bitmap_shape[0]: # y vs rows
                    continue
                
                # is the potential move blocked
                if path_bitmask & obstacle_bitmask:
                    continue

                assert len(move_name) == 6
                assert move_name[:5] == "under"
                underground_size = int(move_name[5])
                
                # default behavior
                # yield cost(ds, iron_cost, direction, previous_direction), ("underground start/end pair", x+dx, y+dy, direction, underground_size)
                yield BuildUnderground(x+dx, y+dy, direction, previous_direction, underground_size)


def manhattan_distance(nxy, goal):
    return (goal[0] - nxy[0]) + (goal[1] - nxy[1])

class NoPathExists(Exception): pass

def astar(start, goal, obstacle_grid, obstacle_table, starting_direction=None, heuristic=manhattan_distance):
    #            f, xy     # ordering matters because heapq prefers first index
    frontier = [(0, start)]
    g_dict = {start: 0}
    came_from = {}
    came_from[start] = (None, 0, None)
    while frontier:

        f, xy = heapq.heappop(frontier)
        if xy == goal:
            return reconstruct(came_from, xy)
        
        _, depth, prev_operation = came_from[xy]
        
        # print((f, xy))
        for operation in neighbors(obstacle_grid, obstacle_table, prev_operation, xy):
            # g_cost = operation.g_cost
            # print(" ", g_cost, operation_data)
            # operation_kind = operation_data[0]
            # if operation_kind == "belt segment":
            #     nxy = operation_data[2:4]
            # else:
            #     raise ValueError((operation_kind, operation_data))
            nxy = (operation.x, operation.y)
            g = g_dict[xy] + operation.g_cost
            if g < g_dict.get(nxy, np.inf):
                f = g + heuristic(nxy, goal)
                heapq.heappush(frontier, (f, nxy))
                g_dict[nxy] = g # pyright: ignore[reportArgumentType]
                came_from[nxy] = (xy, depth+1, operation)
        # input()
    raise NoPathExists(start, goal)


def reconstruct(came_from, xy):
    depth = came_from[xy][1]
    path = [None]*depth
    while xy in came_from:
        xy, i, metadata = came_from[xy]
        path[i-1] = (xy, metadata)
    return path



def apply_belt_path(entity_grid, path_operations):
    previous_operation = None
    for operation in path_operations:
        raise NotImplementedError("todo add entities to the grid, making sure to consolidate belt pieces into belt segments")

        operation_kind = operation[0]

        if operation_kind == "belt segment":
            _, segment_startx, segment_starty, segment_direction, segment_length = operation

            new_obstacle_id = len(obstacle_table)
            obstacle_table.append((operation_kind, segment_startx, segment_starty, segment_direction, segment_length))

            cardinal, dx, dy = DIRECTIONS[segment_direction]
            for ds in range(segment_length):
                x = segment_startx + dx*ds
                y = segment_startx + dy*ds
                obstacle_grid[y, x] = new_obstacle_id

        else:
            raise ValueError((operation_kind, operation))






        (x, y), (direction, move_type) = path[i]
        # nx, ny = path[i+1][0]

        cardinal, dx, dy = DIRECTIONS[direction]
        if move_type in BELT_MOVESET:
            ds = BELT_MOVESET[move_type][0]
        elif move_type in UNDERGROUND_MOVESET:
            ds = UNDERGROUND_MOVESET[move_type][0]
        else:
            raise ValueError(move_type)

        b = 0
        b |= (BELT_TO_NORTH, BELT_TO_EAST, BELT_TO_SOUTH, BELT_TO_WEST)[direction]

        bu = 0
        bu |= b

        if move_type == "belt": pass
        elif move_type == "under1": bu |= 1 << 4
        elif move_type == "under2": bu |= 2 << 4
        elif move_type == "under3": bu |= 3 << 4
        elif move_type == "under4": bu |= 4 << 4
        else: raise ValueError(move_type)

        # b = 0
        # if y > ny:
        #     b |= BELT_TO_NORTH
        # if x < nx:
        #     b |= BELT_TO_EAST
        # if y < ny:
        #     b |= BELT_TO_SOUTH
        # if x > nx:
        #     b |= BELT_TO_WEST

        # assert (b > 0) & ((b & (b - 1)) == 0) # check if only one bit is set (exactly one output direction)
        # assert belt_bitmap[y, x] == 0, (x, y) # check if there is not already a belt in that position

        # if ny < belt_bitmap.shape[0] and nx < belt_bitmap.shape[1]:
        #     belt_bitmap[ny, nx] |= b<<4 # set next cell to expect an input belt

        
        belt_bitmap[y, x] = b

        if move_type != "belt": # means it is an underground
            belt_bitmap[y + dy, x + dx] = bu
            belt_bitmap[y + (ds-1)*dy, x + (ds-1)*dx] = bu





