"""

initital psuedocode for A* generated by Claude Sonnet

"""



import heapq
import numpy as np

BELT_TO_NORTH           = 0b0001
BELT_TO_EAST            = 0b0010
BELT_TO_SOUTH           = 0b0100
BELT_TO_WEST            = 0b1000
BELT_INPUT_GOING_NORTH  = BELT_TO_NORTH << 4
BELT_INPUT_GOING_EAST   = BELT_TO_EAST  << 4
BELT_INPUT_GOING_SOUTH  = BELT_TO_SOUTH << 4
BELT_INPUT_GOING_WEST   = BELT_TO_WEST  << 4

DIRECTIONS = [
    ("n",  0, -1 ),
    ("e",  1,  0 ),
    ("s",  0,  1 ),
    ("w", -1,  0 )
]

BELT_MOVESET = {
    #           ds  iron_cost path_bitmask                  can_turn_next
    "belt":   ( 1,   3.0,     0b00000001   ),   # np.array((1,)),            True          ),
    "under1": ( 4,  21.5,     0b00000101   ),   # np.array((1,0,1,1)),       False         ),
    "under2": ( 5,  21.5,     0b00001001   ),   # np.array((1,0,0,1,1)),     False         ),
    "under3": ( 6,  21.5,     0b00010001   ),   # np.array((1,0,0,0,1,1)),   False         ),
    "under4": ( 7,  21.5,     0b00100001   )    # np.array((1,0,0,0,0,1,1)), False         )
}
MAX_BELT_MOVESET_LENGTH = max(BELT_MOVESET.values(), key=lambda x:x[0])[0]


def neighbors(xy, obstacle_bitmap):
    # assert occupancy_bitmap.shape == belt_bitmap.shape
    bitmap_shape = obstacle_bitmap.shape

    for (direction, (cardinal, dx, dy)) in enumerate(DIRECTIONS):
        # if direction == (previous_direction + 2) % 4:
        #     continue # cannot double back

        mask_minx = min(xy[0] + dx, xy[0] + dx*MAX_BELT_MOVESET_LENGTH)
        mask_maxx = max(xy[0] + dx, xy[0] + dx*MAX_BELT_MOVESET_LENGTH)
        mask_miny = min(xy[1] + dy, xy[1] + dy*MAX_BELT_MOVESET_LENGTH)
        mask_maxy = max(xy[1] + dy, xy[1] + dy*MAX_BELT_MOVESET_LENGTH)
        
        obstacle_bool_arr = (obstacle_bitmap[mask_miny:mask_maxy+1, mask_minx:mask_maxx+1] > 0).ravel()
        if dx == -1 or dy == -1:
            obstacle_bool_arr = obstacle_bool_arr[::-1]
        obstacle_bitmask = int.from_bytes(np.packbits(obstacle_bool_arr, bitorder="little").tobytes())

        for (ds, iron_cost, path_bitmask) in BELT_MOVESET.values():
            nxy = (xy[0] + ds*dx, xy[1] + ds*dy)

            # is it in bounds (one over bounds is okay because we don't place the last belt entity)
            if nxy[0] < -1:
                continue
            if nxy[1] < -1:
                continue
            if nxy[0] > bitmap_shape[1]: # x vs columns
                continue
            if nxy[1] > bitmap_shape[0]: # y vs rows
                continue
            
            # is the potential move blocked
            if path_bitmask & obstacle_bitmask:
                continue
            
            cost = ds*1.0 + iron_cost*0.000001
            
            # default behavior
            yield nxy, cost


def reconstruct(came_from, node_xy, depth):
    path = [None]*(depth+1)
    for i in range(depth, -1, -1):
        path[i] = node_xy
        node_xy = came_from.get(node_xy)
    assert node_xy not in came_from
    return path

def manhattan_distance(nxy, goal):
    return (goal[0] - nxy[0]) + (goal[1] - nxy[1])

class NoPathExists(Exception): pass

def astar(start, goal, obstacle_bitmap, heuristic=manhattan_distance):
    # frontier format:
    #            node_xy, h_cost, depth
    frontier = [(start,   0,      0)]
    g = {start: 0}
    came_from = {}
    while frontier:

        # print(frontier)
        # input()

        node_xy, _, depth = heapq.heappop(frontier)
        if node_xy == goal:
            return reconstruct(came_from, node_xy, depth)
        for nxy, cost in neighbors(node_xy, obstacle_bitmap):
            new_g = g[node_xy] + cost
            if new_g < g.get(nxy, np.inf):
                g[nxy] = new_g
                came_from[nxy] = node_xy
                new_h = new_g + heuristic(nxy, goal)
                heapq.heappush(frontier, (nxy, new_h, depth+1))
    raise NoPathExists(start, goal)




def apply_belt_path(belt_bitmap, path):
    for i in range(len(path)-1): # skip the last one because we don't actually need to add a belt there

        b = 0
        if path[i][1] > path[i+1][1]:
            b |= BELT_TO_NORTH
        if path[i][0] < path[i+1][0]:
            b |= BELT_TO_EAST
        if path[i][1] < path[i+1][1]:
            b |= BELT_TO_SOUTH
        if path[i][0] > path[i+1][0]:
            b |= BELT_TO_WEST
        assert (b > 0) & ((b & (b - 1)) == 0) # check if only one bit is set (exactly one output direction)

        assert belt_bitmap[path[i][1], path[i][0]] & 0b1111 == 0, (path[i][0], path[i][1]) # check if there is not already a belt in that position
        belt_bitmap[path[i][1], path[i][0]] = b # set belt output direction
        if path[i+1][1] < belt_bitmap.shape[0] and path[i+1][1] < belt_bitmap.shape[1]:
            belt_bitmap[path[i+1][1], path[i+1][1]] |= b<<4 # set next cell to expect an input belt



