"""

initital psuedocode AI Generated by Claude Sonnet

"""



import heapq
import numpy as np

BELT_TO_NORTH           = 0b0001
BELT_TO_EAST            = 0b0010
BELT_TO_SOUTH           = 0b0100
BELT_TO_WEST            = 0b1000
BELT_INPUT_GOING_NORTH  = BELT_TO_NORTH << 4
BELT_INPUT_GOING_EAST   = BELT_TO_EAST  << 4
BELT_INPUT_GOING_SOUTH  = BELT_TO_SOUTH << 4
BELT_INPUT_GOING_WEST   = BELT_TO_WEST  << 4

BELT_MOVESET = {
         # dx, dy,  cost #
    "n": (  0, -1,  1    ),
    "e": (  1,  0,  1    ),
    "s": (  0,  1,  1    ),
    "w": ( -1,  0,  1    ),
}


def neighbors(xy, occupancy_bitmap, belt_bitmap, goal):
    assert occupancy_bitmap.shape == belt_bitmap.shape
    bitmap_shape = occupancy_bitmap.shape

    for (name, (dx, dy, default_cost)) in BELT_MOVESET.items():
        nxy = (xy[0] + dx, xy[1] + dy)
        cost = default_cost
        
        if nxy == goal:
            yield nxy, cost
            continue

        # is it in bounds
        if nxy[0] < 0:
            continue
        if nxy[1] < 0:
            continue
        if nxy[0] >= bitmap_shape[1]: # x vs columns
            continue
        if nxy[1] >= bitmap_shape[0]: # y vs rows
            continue
        
        # is it occupied
        if occupancy_bitmap[nxy[1], nxy[0]] != 0:
            continue
        
        # is there a belt in the way
        if (belt_bitmap[nxy[1], nxy[0]] & 0b1111) != 0:
            continue
        
        # default behavior
        yield nxy, cost
        continue

def reconstruct(came_from, node_xy, depth):
    path = [None]*(depth+1)
    for i in range(depth, -1, -1):
        path[i] = node_xy
        node_xy = came_from.get(node_xy)
    assert node_xy not in came_from
    return path

def manhattan_distance(nxy, goal):
    return (goal[0] - nxy[0]) + (goal[1] - nxy[1])

def astar(start, goal, occupancy_bitmap, belt_bitmap, heuristic=manhattan_distance):
    # frontier format:
    #            node_xy, h_cost, depth
    frontier = [(start,   0,      0)]
    g = {start: 0}
    came_from = {}
    while frontier:

        # print(frontier)
        # input()

        node_xy, _, depth = heapq.heappop(frontier)
        if node_xy == goal:
            return reconstruct(came_from, node_xy, depth)
        for nxy, cost in neighbors(node_xy, occupancy_bitmap, belt_bitmap, goal):
            new_g = g[node_xy] + cost
            if new_g < g.get(nxy, np.inf):
                g[nxy] = new_g
                came_from[nxy] = node_xy
                new_h = new_g + heuristic(nxy, goal)
                heapq.heappush(frontier, (nxy, new_h, depth+1))
    return None




def apply_belt_path(belt_bitmap, path):
    for i in range(len(path)-1): # skip the last one because we don't actually need to add a belt there

        b = 0
        if path[i][1] > path[i+1][1]:
            b |= BELT_TO_NORTH
        if path[i][0] < path[i+1][0]:
            b |= BELT_TO_EAST
        if path[i][1] < path[i+1][1]:
            b |= BELT_TO_SOUTH
        if path[i][0] > path[i+1][0]:
            b |= BELT_TO_WEST
        assert (b > 0) & ((b & (b - 1)) == 0) # check if only one bit is set (exactly one output direction)

        assert belt_bitmap[path[i][1], path[i][0]] & 0b1111 == 0 # check if there is not already a belt in that position
        belt_bitmap[path[i][1], path[i][0]] = b # set belt output direction
        belt_bitmap[path[i+1][1], path[i+1][1]] |= b<<4 # set next cell to expect an input belt



