"""

initital psuedocode AI Generated by Claude Sonnet

"""



import heapq
import numpy as np

BELT_TO_NORTH           = 0b0001
BELT_TO_EAST            = 0b0010
BELT_TO_SOUTH           = 0b0100
BELT_TO_WEST            = 0b1000
BELT_INPUT_GOING_NORTH  = BELT_TO_NORTH << 4
BELT_INPUT_GOING_EAST   = BELT_TO_EAST  << 4
BELT_INPUT_GOING_SOUTH  = BELT_TO_SOUTH << 4
BELT_INPUT_GOING_WEST   = BELT_TO_WEST  << 4

BELT_DIRECTIONS = (
    (0, -1, "n"),
    (1,  0, "e"),
    (0,  1, "s"),
    (0,  0, "w"),
)

def edge_cost(x, y, nx, ny, direction_name, occupancy_bitmap, belt_bitmap):
    assert occupancy_bitmap.size == belt_bitmap.size
    bitmap_size = occupancy_bitmap.size

    # is it in bounds
    if nx < 0:
        return None
    if ny < 0:
        return None
    if nx > bitmap_size[1]: # columns
        return None
    if ny > bitmap_size[0]: # rows
        return None
    
    # is it occupied
    if occupancy_bitmap[ny, nx] != 0:
        return None
    
    # is there a belt in the way
    if (belt_bitmap[ny, nx] & 0b1111) != 0:
        return None
    
    # default unweighted cost
    return 1




def neighbors(x, y, occupancy_bitmap, belt_bitmap):
    for dx, dy, direction_name in BELT_DIRECTIONS:  # 4-connected for belts
        nx, ny = x + dx, y + dy
        # if not in_bounds(nx, ny) or is_obstacle(nx, ny, bitmaps):
        #     continue
        e_c = edge_cost(x, y, nx, ny, direction_name, occupancy_bitmap, belt_bitmap)
        if e_c == None:
            continue
        yield (nx, ny), e_c

def reconstruct(came_from, node):
    reverse_path = []
    while node:
        reverse_path.append(node)
        node = came_from.get(node)
    return reversed(reverse_path)

def heuristic(nxy, goal):
    # manhattan distance
    return (goal[0] - nxy[0]) + (goal[1] - nxy[1])

def astar(start, goal, occupancy_bitmap, belt_bitmap, heuristic):
    frontier = [(0, start)]
    g = {start: 0}
    came_from = {}
    while frontier:
        _, node = heapq.heappop(frontier)
        if node == goal:
            return reconstruct(came_from, node)
        for nxy, cost in neighbors(node[0], node[1], occupancy_bitmap, belt_bitmap):
            new_g = g[node] + cost
            if new_g < g.get(nxy, np.inf):
                g[nxy] = new_g
                came_from[nxy] = node
                heapq.heappush(frontier, (new_g + heuristic(nxy, goal), nxy))
    return None




def apply_belt_path(belt_bitmap, path):
    for i in range(len(path)-1): # skip the last one because we don't actually need to add a belt there

        b = 0
        if path[i].y > path[i+1].y:
            b |= BELT_TO_NORTH
        if path[i].x < path[i+1].x:
            b |= BELT_TO_EAST
        if path[i].y < path[i+1].y:
            b |= BELT_TO_SOUTH
        if path[i].x > path[i+1].x:
            b |= BELT_TO_WEST

        # print(i)
        # print(path[i].x, path[i].y)
        # print(path[i+1].x, path[i+1].y)
        # input()
            
        assert belt_bitmap[path[i].y, path[i].x] & 0b00001111 == 0
        belt_bitmap[path[i].y, path[i].x]        |= b
        belt_bitmap[path[i+1].y, path[i+1].x]    |= b<<4 # convert "to" format to "from" format



