"""

initital psuedocode AI Generated by Claude Sonnet

"""



import heapq

def neighbors(x, y, bitmaps):
    for dx, dy, direction in DIRECTIONS:  # 4-connected for belts
        nx, ny = x + dx, y + dy
        if not in_bounds(nx, ny) or is_obstacle(nx, ny, bitmaps):
            continue
        yield (nx, ny), edge_cost(x, y, nx, ny, direction, bitmaps)

def astar(start, goal, bitmaps, heuristic):
    frontier = [(0, start)]
    g = {start: 0}
    came_from = {}
    while frontier:
        _, node = heapq.heappop(frontier)
        if node == goal:
            return reconstruct(came_from, node)
        for nbr, cost in neighbors(*node, bitmaps):
            new_g = g[node] + cost
            if new_g < g.get(nbr, float("inf")):
                g[nbr] = new_g
                came_from[nbr] = node
                heapq.heappush(frontier, (new_g + heuristic(nbr, goal), nbr))
    return None


